/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rythm.game;

import java.sql.Statement;
import java.util.ArrayList;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Connection;
import javax.swing.JOptionPane;
import java.sql.*;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author ASUS
 */
public class HIGHSCORE extends javax.swing.JFrame {

    /**
     * Creates new form HIGHSCORE
     */
    public HIGHSCORE() {
        initComponents();
        show_user();
    }

    public ArrayList<User> userList(){
        ArrayList<User> userList = new ArrayList<>();
        try {
//            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
//            String url = "jdbc:sqlserver://localhost\\sqlexpress;databaseName=InformationUser";
//            Connection connection = DriverManager.getConnection(url);
            String url = "jdbc:sqlserver://localhost\\sqlexpress;databaseName=InformationUser";
            String userid = "sa";
            String password = "atb1230101010";
            Connection connection = DriverManager.getConnection(url,userid,password);
            String query = "SELECT * FROM ID ORDER BY DIEM DESC";
            Statement st = connection.createStatement();
            ResultSet rs = st.executeQuery(query);
            User user;
            while(rs.next()){
                user = new  User(rs.getString("ID"),rs.getString("TenNguoiDung"),rs.getFloat("DIEM"));
                userList.add(user);             
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        return userList;
    }
    public void show_user(){
        ArrayList<User> list = userList();
        DefaultTableModel model = (DefaultTableModel)jTable1_Display_User.getModel();
        Object[] row = new Object[3];
        for(int i=0;i<list.size();i++){
            row[0] = list.get(i).getID();
            row[1] = list.get(i).getTenNguoiDung();
            row[2] = list.get(i).getDiem();
            model.addRow(row);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1_Display_User = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jTable1_Display_User.setFont(new java.awt.Font("Lucida Sans Unicode", 3, 11)); // NOI18N
        jTable1_Display_User.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Tên Người Chơi", "Điểm số"
            }
        ));
        jTable1_Display_User.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_NEXT_COLUMN);
        jTable1_Display_User.setGridColor(new java.awt.Color(0, 0, 0));
        jTable1_Display_User.setSelectionBackground(new java.awt.Color(0, 0, 0));
        jTable1_Display_User.setSelectionForeground(new java.awt.Color(0, 0, 0));
        jScrollPane1.setViewportView(jTable1_Display_User);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(0, 0, 780, 410);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, -30, 820, 1080);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HIGHSCORE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HIGHSCORE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HIGHSCORE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HIGHSCORE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HIGHSCORE().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1_Display_User;
    // End of variables declaration//GEN-END:variables
}
